name: "Run unit tests"
on:
  push:

jobs:
  setup:
    uses: ./.github/workflows/prepare-env.yaml
    secrets: inherit
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          pip install pytest-md-report
          pytest --md-report --cov=flood_prediction tests --cov-report term-missing >> $GITHUB_STEP_SUMMARY
